# Generated by Django 4.1.3 on 2022-12-14 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tienda.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrito', models.IntegerField(blank=True, null=True, validators=[tienda.models.validar_numero_entero])),
                ('producto', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('vasija', 'vasija'), ('macetero', 'macetero'), ('planta', 'planta')], max_length=100, validators=[tienda.models.validar_tipo_producto])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='boletas', validators=[tienda.models.validar_dimensiones_imagen])),
                ('precio', models.IntegerField(validators=[tienda.models.validar_numero_entero])),
                ('cantidad', models.IntegerField(validators=[tienda.models.validar_numero_entero])),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='carrusel', validators=[tienda.models.validar_dimensiones_imagen])),
                ('item_titulo', models.CharField(max_length=1024)),
                ('item_parrafo', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vasija', 'vasija'), ('macetero', 'macetero'), ('planta', 'planta')], max_length=100, validators=[tienda.models.validar_tipo_producto])),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField(validators=[tienda.models.validar_numero_entero])),
                ('descripcion', models.CharField(max_length=1024)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos', validators=[tienda.models.validar_dimensiones_imagen])),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField(validators=[tienda.models.validar_numero_entero])),
                ('descripcion', models.CharField(max_length=1024)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios', validators=[tienda.models.validar_dimensiones_imagen])),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='testimonios', validators=[tienda.models.validar_dimensiones_foto])),
                ('nombre_cliente', models.CharField(max_length=1024)),
                ('profesion_cliente', models.CharField(max_length=1024)),
                ('testimonio_cliente', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('duracion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('precio_total', models.IntegerField(validators=[tienda.models.validar_numero_entero])),
                ('estado', models.CharField(choices=[('En espera', 'En espera'), ('Pagar', 'Pagar'), ('Pagado', 'Pagado'), ('Finalizado', 'Finalizado')], default='En espera', max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('precio_total', models.IntegerField(blank=True, null=True, validators=[tienda.models.validar_numero_entero])),
                ('estado', models.CharField(choices=[('En espera', 'En espera'), ('Pagar', 'Pagar'), ('Pagado', 'Pagado'), ('Retirado', 'Retirado')], default='En espera', max_length=100)),
                ('json', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DatosCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
