# Generated by Django 4.1.4 on 2022-12-15 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocarrito',
            name='json',
        ),
    ]
