# Generated by Django 4.1.3 on 2022-12-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_pedidocarrito_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoservicio',
            name='terminos_acordados',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
