# Generated by Django 4.1.3 on 2022-12-19 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_pedidoservicio_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoservicio',
            name='area',
        ),
    ]
